-- Create the main table to store all complaints
CREATE TABLE complaints (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamz DEFAULT now(),
  category text,
  description text,
  image_url text,
  latitude float8,
  longitude float8,
  neighborhood text
);

-- Note:
-- After creating the table, you must also:
-- 1. Create a Storage Bucket named "complaint_images".
-- 2. Make the bucket PUBLIC.
-- 3. Add a policy to the bucket to allow INSERT for the "anon" role.